In [2]:
import numpy as np
norm = lambda a : np.linalg.norm(a)
dot = lambda a,b : np.dot(a,b)
funky = lambda a,b : a[0]* b[0] - (a[0]*b[1] + a[1]*b[0]) + 2 * a[1]*b[1]
print(norm([3,4]))
print(dot([1,2],[3,4]))
    

5.0
11


In [3]:
#⟨x, y⟩ := x1y1 − (x1y2 + x2y1) + 2x2y2
print(1 * 3 - (1 * 4 + 2 * 3) + 2* 2)

-3


a set of basis vectors is a bilinear mapping

In [4]:
lamb = 2
phi = 3
b1 ,b2, b3 = np.array([[1,2,3],[0,1,0] , [0,0,1]])
b1, b2, b3 = np.array([[1,2],[2,3], [3,-2]])
print(funky(lamb * b1 + phi * b2, b3))
print(lamb * funky(b1,b3) + phi * funky(b2, b3))
# print(np.dot(b1,b2))
# print(np.dot(b1, 2 * np.asarray(b2)) == 2 * np.dot(b1, b2))

-51
-51


In [5]:
B = np.array([[1,1], [2,1]])
psi = np.array([2,3])
lamb = np.array([4,5])

xhat = psi.reshape(-1,1)
yhat = lamb.reshape(-1,1)
print('xhat', xhat)
print('yhat', yhat)
# print(np.dot(psi, lamb))
summation = 0 
for i in range(2):
    for j in range(2):
        summation+=xhat[i] * np.dot(B[i], B[j]) * yhat[j]
print('B shape', B.shape)
A = B.T @ B
print('A', A)
print('xhat', xhat)
print('shape of x and y', xhat.shape)
print(summation)

print(xhat.T @ A @ yhat)

xhat [[2]
 [3]]
yhat [[4]
 [5]]
B shape (2, 2)
A [[5 3]
 [3 2]]
xhat [[2]
 [3]]
shape of x and y (2, 1)
[157]
[[136]]


In [6]:
B = np.array([[1,0], [2,1]])
psi = np.array([2,3])
lamb = np.array([4,5])

x = B @ psi.reshape(-1,1)
y = B @ lamb.reshape(-1,1)

print(B.shape)
print(B)
print(x.T @ y)

summation = 0 
for i in range(2):
    for j in range(2):
        summation+=psi[i] * np.dot(B.T[i], B.T[j]) * lamb[j]
print(summation)

A = B.T @ B
print(A)
xhat = psi.reshape(-1,1)
yhat = lamb.reshape(-1,1)
print(xhat.T @ A @ yhat)

(2, 2)
[[1 0]
 [2 1]]
[[99]]
99
[[5 2]
 [2 1]]
[[99]]


Dot product: ${x_{1}y_{1} + x_{2}y_{2}}$

Euclidean Metric: $\sqrt{(x_{1}-y_{1})^{2} + (x_{2}-y_{2})^2}$

In [7]:
# cauchy shwarz? show its relevance
#example 3.5 what are the ramifications of using a different inner product. When is it even an inner product again?
# norm definition
a = [1, -1, 1]
b = [-10, -1, 1]

In [8]:
# compare euclidean distance and dot product 
np.dot(a, a)

np.linalg.norm

<function numpy.linalg.norm>

### Orthogonal Matrix
    If a matrix is orthogonal it is also orthonormal
    A and B here are both orthogonal matrix    

In [9]:
A = np.array([[1,0],[0,1]])
B = np.array([[1/np.sqrt(2),1/np.sqrt(2)],[1/np.sqrt(2),-1/np.sqrt(2)]])
x = np.array([1,2])
print("Norm of x", np.linalg.norm(x)**2)
print(A @ x, '| | = ', np.linalg.norm(A@x) ** 2)
print(B.T @ x, '| | = ', np.linalg.norm(B @ x))

Norm of x 5.000000000000001
[1 2] | | =  5.000000000000001
[ 2.12132034 -0.70710678] | | =  2.2360679774997894


In [10]:
# A = []
# V = np.array([[2,0],[0,1]])
# u1 = V[:,0]/np.linalg.norm(V[:,0])
# A.append(u1)
# v2 = V[:,1]
# u2 = (v2 - v2 @ u1)/np.linalg.norm(v2)
# A.append(u2)

# print(u1)
# print(u2)
# print(A)
def gram_schmidt(V):
    '''
    Input: set of linearly independent vectors V (n,k)
    Output: set of orthonormal basic vectors A (n,k)
    '''
    V = np.asarray(V)
    A = []
    u1 = V[:,0]/np.linalg.norm(V[:,0])
    A.append(u1)
    for i in range(1, len(V)):
        vi = V[:,i].reshape(len(V[:,i]), 1)
        proj = 0
        for j in range(len(A)):
            u = np.asarray(A).T[:,j]
            u = u.reshape(len(u),1)
            proj += vi *u *u
        ui = (vi - proj)/np.linalg.norm(vi)
        A.append(ui.reshape(len(ui)))
    return np.asarray(A)

V = [[3,0,0],[0,4,0],[0,0,5]]
print(gram_schmidt(V))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 3.6 - 4.0

### Old

Subspace
- Requirement i) v + w is closed
- Requirement ii) c*v is closed
- 0 exists
- Examples like line, plane, single vector, whole space
- Forgot: how many dimensions in a guy again? Same as vector space right? Don't confuse dimensions and number of basis. Has to be strictly less than.



Affine space*
- Off the origin

What are the types of morphisms?
- homomorphism mapping of algebraic structure, linear map. Same as functor in category theory
- iso V -> W linear bijective, invertible. benefit just renaming graph replace with what you know
- endo V > Vlinear, morphism to self. Endo that is isomorphism is automorphism
- automorphism V -> V linear and bijective, isomorphism to self but better than endo because bijective

### New

Orthogonal Complement
- You can describe a plane with a vector 'normal'. generalizes to hyperplane
- x can be uniquely decomposed

Inner product of functions
- show this is true with sin(x) cos(x), function has limit 

Orthogonal projection
- affine
- idempotent

Rotations
- preserves distances, lengths, angles
- not commutative 3D and onward

Gram-Schmidt

linear transformation vs projection 

represent linear transformation with matrix

givens

better viiusalizaion

### Show/prove/experiments

Rotation

projections

Representing a space with hyperplane

What doeds it mean for functions to be orthogonal? Inner function of product 

f o g = f(g(x))


In [11]:
# space    [1 0 0], [0 1 0], [0 0 1]


$x = \sum \lambda_{m}b_{m}$

In [12]:
subspace A [1 0], [0 1]

subspace A_c [0 0 1]

SyntaxError: invalid syntax (<ipython-input-12-98e4d0eed2dc>, line 1)

## Determinant

In [13]:
A = np.array([[1,2,3],[3,1,2],[0,0,1]])
A_1= np.array([A[0],A[1] + 2* A[2], A[2]])
A_order = np.array([A[2],A[1],A[0]])
A_lamb = np.array([A[0],A[1],5 * A[2]])
print('regular',np.linalg.det(A))
print('scaled row addtion to another row',np.linalg.det(A_1))
print('order of row change', np.linalg.det(A_order))
print('Scaled one row of A only ', np.linalg.det(A_lamb))

regular -5.000000000000001
scaled row addtion to another row -5.000000000000001
order of row change 5.000000000000001
Scaled one row of A only  -25.000000000000007


Hello

## Eigenvectors and Eigenvalues


### Really cool paper in Nature about how the brain uses eigenvectors for facial recognition: https://www.sciencedirect.com/science/article/pii/S009286741730538X
- the experiment done is well-thought out. They use real eigenvectors, and map neural cells onto that plane. By then changing faces you can guess which neurons will fire based on how they have been mapped onto your eigenspace.

Trace is useful because the trace is equal to the sum of the eigenvectors. Therefore you can guess some of the remaining eigenvalues when you have a few

In [54]:
A = 5 * np.random.rand(3,3)
A

array([[0.91660753, 3.03553336, 1.87171306],
       [4.84970385, 0.15544581, 1.49963581],
       [3.36814714, 0.54331395, 4.60469438]])

In [55]:
# make it positive semidefinite
A += 10 * np.eye(3,3)

Case where we take the eigenvectors of $A$

In [56]:
values, vectors = np.linalg.eig(A)
largestvalue = values[np.argmax(values)]
largestvec = vectors[np.argmax(values)]
newvec = A @ largestvec
print('determinant', np.linalg.det(A))
print('values', values)
print('vectors', vectors)
print('largest eigenvector', largestvec)
print('largest eigenvalue', largestvalue)
print('norm before transformation', np.linalg.norm(largestvec))
print('norm after transformation', np.linalg.norm(newvec))
print('scale factor = ', np.linalg.norm(newvec)/np.linalg.norm(vectors[0]))


values [17.07505163  6.58843285 12.01326322]
vectors [[-0.46454453 -0.62057131 -0.43525846]
 [-0.48601431  0.75563848 -0.58120347]
 [-0.74026244  0.20952741  0.68757007]]
largest eigenvector [-0.46454453 -0.62057131 -0.43525846]
largest eigenvalue 17.075051633591308
norm before transformation 0.8890220991911129
norm after transformation 14.606744966308884
scale factor =  16.430125842314833


Case where we take the eigenvectors of $A^TA$

In [57]:
values, vectors = np.linalg.eig(A.T @ A)
largestvalue = values[np.argmax(values)]
largestvec = vectors[np.argmax(values)]
newvec = A @ largestvec
print('values', values)
print('vectors', vectors)
print('largest eigenvector', largestvec)
print('largest eigenvalue', largestvalue)
print('norm before transformation', np.linalg.norm(largestvec))
print('norm after transformation', np.linalg.norm(newvec))
print('scale factor = ', np.linalg.norm(newvec)/np.linalg.norm(vectors[0]))

values [299.08522439  42.31084139 144.33234423]
vectors [[-0.59547053 -0.66538751 -0.45019363]
 [-0.3786105   0.72667285 -0.573237  ]
 [-0.70856823  0.1708977   0.68463497]]
largest eigenvector [-0.59547053 -0.66538751 -0.45019363]
largest eigenvalue 299.08522438525114
norm before transformation 0.9999999999999999
norm after transformation 16.557000258195732
scale factor =  16.557000258195735


## Investigation Condition of a Matrix

Defined as $\frac{|A|}{|A^{-1}|}$

In [50]:
values, vectors = np.linalg.eig(A)
largestvalue = values[np.argmax(values)]
largestvec = vectors[np.argmax(values)]
newvec = A @ largestvec
print('values', values)
print('vectors', vectors)
print('largest eigenvector', largestvec)
print('largest eigenvalue', largestvalue)
print('norm before transformation', np.linalg.norm(largestvec))
print('norm after transformation', np.linalg.norm(newvec))
print('scale factor = ', np.linalg.norm(newvec)/np.linalg.norm(vectors[0]))
print('condition number', np.linalg.cond(A.T @ A))
print('sum of singular values', np.sum(values))

values, vectors = np.linalg.eig(A.T @ A)
largestvalue = values[np.argmax(values)]
largestvec = vectors[np.argmax(values)]
print('largest singular value/smallest', values[np.argmax(values)]/values[np.argmin(values)])

values [0.39131003 0.50282386 0.76709185]
vectors [[ 0.49318113 -0.41641998  0.40023597]
 [-0.78380105 -0.60369857  0.64377513]
 [ 0.37739672  0.67981058  0.65219993]]
largest eigenvector [0.37739672 0.67981058 0.65219993]
largest eigenvalue 0.7670918464894264
norm before transformation 1.014857362380905
norm after transformation 0.777369662179548
scale factor =  1.0235443290888007
condition number 4.0249400776458595
sum of singular values 1.661225733447936
largest singular value 4.024940077645863


In [52]:
A = np.array([[1,0,0],
             [0,3,0],
             [0,0,1]])
A.T @ A

array([[1, 0, 0],
       [0, 9, 0],
       [0, 0, 1]])

In [53]:
A.T

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 1]])